using System.Data;
using Dapper;

namespace FastJobs.Persistence;

public class PostgresJobTableInitializer : ISchemaInitializer
{
    int ISchemaInitializer.Order => 0;

    private const string CreateTableSql = @"
    CREATE TABLE IF NOT EXISTS Jobs
    (
        Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        AfterActionId BIGINT NULL,

        JobType VARCHAR(50) NOT NULL DEFAULT '',

        TypeName VARCHAR(500) NOT NULL,
        MethodName VARCHAR(200) NOT NULL,

        MethodDeclaringTypeName VARCHAR(200),

        ParameterTypeNamesJson TEXT NOT NULL,
        ArgumentsJson TEXT NOT NULL,

        Queue VARCHAR(100) NOT NULL,

        StateName VARCHAR(50) NOT NULL,

        RetryCount INT NOT NULL DEFAULT 0,
        MaxRetries INT NOT NULL DEFAULT 3,

        Priority INT NOT NULL DEFAULT 0,

        misfirePolicy INT NOT NULL DEFAULT 0,
        ScheduledRunAt TIMESTAMPTZ NULL,
        CreatedAt TIMESTAMPTZ NOT NULL,
        ExpiresAt TIMESTAMPTZ NULL,

        StateId BIGINT NOT NULL
    );";

    private const string CreateIndexQueueSql = @"
    CREATE INDEX IF NOT EXISTS IX_Jobs_Queue_State_Priority_CreatedAt
    ON Jobs (Queue, StateName, Priority DESC, CreatedAt);";
    private const string CreateIndexStateSql = @"
    CREATE INDEX IF NOT EXISTS IX_Jobs_StateName_StateID
    ON Jobs (StateName, StateID);";
    private const string CreateIndexJobTypeSql = @"
    CREATE INDEX IF NOT EXISTS IX_Jobs_JobType
    ON Jobs (JobType);";

    public async Task EnsureCreatedAsync(IDbConnection connection)
    {
        await connection.ExecuteAsync(CreateTableSql);
        await connection.ExecuteAsync(CreateIndexQueueSql);
        await connection.ExecuteAsync(CreateIndexStateSql);
        await connection.ExecuteAsync(CreateIndexJobTypeSql);
    }
}
