using System.Data;
using Dapper;

namespace FastJobs.Persistence;

public class PostgresQueueTableInitializer : ISchemaInitializer
{
    int ISchemaInitializer.Order => 1;

    private const string CreateTableSql = @"
    CREATE TABLE IF NOT EXISTS Queue
    (
        Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        QueueName VARCHAR(500) NOT NULL,
        DequeuedAt TIMESTAMPTZ NULL,
        JobId BIGINT NOT NULL,
        Priority INT NOT NULL DEFAULT 0,
        isDequeued BOOLEAN NOT NULL DEFAULT FALSE,
        IsMisfireRecovery BOOLEAN NOT NULL DEFAULT FALSE,

        CONSTRAINT FK_Queue_Jobs
        FOREIGN KEY (JobId)
        REFERENCES Jobs(Id)
        ON DELETE CASCADE
    );";

    private const string CreateIndexQueueSql = @"
    CREATE INDEX IF NOT EXISTS IX_Queue_QueueName_Priority_Scheduled
    ON Queue (QueueName, Priority DESC, isDequeued);";
    private const string CreateIndexJobIdSql = @"
    CREATE INDEX IF NOT EXISTS IX_Queue_JobId
    ON Queue (JobId);";

    public async Task EnsureCreatedAsync(IDbConnection connection)
    {
        await connection.ExecuteAsync(CreateTableSql);
        await connection.ExecuteAsync(CreateIndexQueueSql);
        await connection.ExecuteAsync(CreateIndexJobIdSql);
    }
}
