using System.Data;
using Dapper;

namespace FastJobs.Persistence;

public class PostgresRecurringJobTableInitializer : ISchemaInitializer
{
    int ISchemaInitializer.Order => 4;

    //   IntervalTicks -- stored as TimeSpan.Ticks
    private const string CreateTableSql = @"
    CREATE TABLE IF NOT EXISTS RecurringJobs
    (
        Id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        JobId            BIGINT NOT NULL,
        NextScheduledID  BIGINT NULL,
        CronExpression   VARCHAR(120) NULL,
        StartTime        TIMESTAMPTZ NOT NULL,
        IntervalTicks    BIGINT NULL,
        NextScheduledTime TIMESTAMPTZ NOT NULL,
        IsConcurrent     BOOLEAN NOT NULL DEFAULT TRUE,
        IsCron           BOOLEAN NOT NULL DEFAULT FALSE,
        ExecutingInstances INT NOT NULL DEFAULT 0,
        ExecutedInstances  INT NOT NULL DEFAULT 0,
        AfterActionExecutionMode INT NOT NULL DEFAULT 0,

        CONSTRAINT FK_RecurringJobs_Jobs
            FOREIGN KEY (JobId)
            REFERENCES Jobs(Id)
            ON DELETE CASCADE
    );";

    private const string CreateIndexJobIdSql = @"
    CREATE INDEX IF NOT EXISTS IX_RecurringJobs_JobId
    ON RecurringJobs (JobId);";

    private const string CreateIndexNextScheduledTimeSql = @"
    CREATE INDEX IF NOT EXISTS IX_RecurringJobs_NextScheduledTime
    ON RecurringJobs (NextScheduledTime ASC);";

    public async Task EnsureCreatedAsync(IDbConnection connection)
    {
        await connection.ExecuteAsync(CreateTableSql);
        await connection.ExecuteAsync(CreateIndexJobIdSql);
        await connection.ExecuteAsync(CreateIndexNextScheduledTimeSql);
    }
}
