using System.Data;
using Dapper;

namespace FastJobs.Persistence;

public class PostgresStateHistoryTableInitialization : ISchemaInitializer
{
    int ISchemaInitializer.Order => 3;

    private const string CreateTableSql = @"
    CREATE TABLE IF NOT EXISTS State
    (
        Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

        StateName VARCHAR(500) NOT NULL,
        Reason VARCHAR(500) NOT NULL,
        data VARCHAR(500) NOT NULL,

        CreatedAt TIMESTAMPTZ NOT NULL,
        DeletedAt TIMESTAMPTZ NULL,

        JobId BIGINT NOT NULL,
        FOREIGN KEY (JobId) REFERENCES Jobs(Id)
        ON DELETE CASCADE
    );";

    private const string CreateIndexStateNameSql = @"
    CREATE INDEX IF NOT EXISTS IX_State_StateName
    ON State (StateName);";
    private const string CreateIndexJobIdSql = @"
    CREATE INDEX IF NOT EXISTS IX_State_JobId
    ON State (JobId);";

    public async Task EnsureCreatedAsync(IDbConnection connection)
    {
        await connection.ExecuteAsync(CreateTableSql);
        await connection.ExecuteAsync(CreateIndexStateNameSql);
        await connection.ExecuteAsync(CreateIndexJobIdSql);
    }
}
