using System.Data;
using Dapper;

namespace FastJobs.Persistence;

public class PostgresWorkerTableInitializer : ISchemaInitializer
{
    int ISchemaInitializer.Order => 5;

    private const string CreateTableSql = @"
    CREATE TABLE IF NOT EXISTS Workers
    (
        Id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        WorkerName     VARCHAR(500) NOT NULL,
        ThreadName     VARCHAR(500) NOT NULL,
        StartedAt      TIMESTAMPTZ  NOT NULL,
        LastHeartbeat  TIMESTAMPTZ  NOT NULL,
        isSleeping     BOOLEAN      NOT NULL DEFAULT FALSE,
        isCrashed      BOOLEAN      NOT NULL DEFAULT FALSE
    );";

    private const string CreateIndexSleepingSql = @"
    CREATE INDEX IF NOT EXISTS IX_Workers_isSleeping
    ON Workers (isSleeping);";

    private const string CreateIndexCrashedSql = @"
    CREATE INDEX IF NOT EXISTS IX_Workers_isCrashed
    ON Workers (isCrashed);";

    public async Task EnsureCreatedAsync(IDbConnection connection)
    {
        await connection.ExecuteAsync(CreateTableSql);
        await connection.ExecuteAsync(CreateIndexSleepingSql);
        await connection.ExecuteAsync(CreateIndexCrashedSql);
    }
}
